update for single surfaces

diff --git a/main b/main
--- a/main
+++ b/main
@@ -14,11 +14,11 @@ singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiledmatl
 #matlab -nodisplay -nosplash -r main
 
 #if [ -s spectrum.json ] && [ -s eigenvectors.mat ]
-#if [ -s spectrum.json ]
-#then
-#	echo 0 > finished
-#else
-#	echo "files missing"
-#	echo 1 > finished
-#	exit 1
-#fi
+if [ -s images.json ]
+then
+	echo 0 > finished
+else
+	echo "files missing"
+	echo 1 > finished
+	exit 1
+fi
